# Use the README file as a reference to customize settings.

Company:
  fields:
    default: name_list, phone, address, segment_list, product_list, plus
    csv: name_list, phone, segment_list, product_list
  application: Sirva.me